### ISSUE TITLE
Make io.prometheus.client.CollectorRegistry.defaultRegistry usable together with iapetos

### ISSUE THREAD

**Issue by delitescere** [clj-commons/iapetos#10]
G'day! This is an awesome library. Thank you so much for making it.

I'm enjoying the ring and jvm wrappers very much. However, I've recently added to my project the [InstrumentedAppender](https://github.com/prometheus/client_java/blob/master/simpleclient_log4j2/src/main/java/io/prometheus/client/log4j2/InstrumentedAppender.java) but it only has a mechanism for registering its collector with the Prometheus Java client's [default registry](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/CollectorRegistry.java#L28).

This means that the ring wrapper exposing metrics at `/metrics` doesn't pick up any non-iapetos collectors because a _different_ default registry is created by iapetos.

I'm wondering if https://github.com/xsc/iapetos/blob/master/src/iapetos/registry.clj#L79 should be more like:

```clojure
(defn create
  ([]
   (IapetosRegistry. "iapetos_registry" (CollectorRegistry/defaultRegistry) {} {})))
  ([registry-name]
   (IapetosRegistry. registry-name (CollectorRegistry.) {} {})))
```

This keeps the "iapetos_registry" name for the default registry for any existing code that might use it, but uses the underlying Prometheus Java client's default registry.

**Comment by xsc** [comment]
@delitescere Thanks for reaching out! I do have a problem, though, with implicitly exposing the default registry, since `create` kinda indicates that a fresh registry is produced. What do you think about just adding `iapetos.core/default-registry`? Then anyone could decide to use it directly and explicitly.

Note to self: [`pushable-collector-registry`](https://github.com/xsc/iapetos/blob/v0.1.6/src/iapetos/export.clj#L87) needs an adjustment for this, allowing a registry to be injected.

**Comment by delitescere** [comment]
@xsc excellent idea.

**Comment by xsc** [comment]
__[Release Notes](https://github.com/xsc/iapetos/releases/tag/v0.1.7)__

**Comment by delitescere** [comment]
Yes, the problem is now there's no surface idempotency. I'm using this in a stuartsierra system, so components can be started, stopped, and restarted. As the same registry is being used, the collectors have already been registered. There's no iapetos mechanism for unregistering at the moment. 

Given I'm using the Prometheus default registry, I can add the following to the "stop" lifecycle task of the component:

`(.clear CollectorRegistry/defaultRegistry)`

This is a little heavy-handed as any collectors my Clojure app doesn't register as part of the "start" lifecycle will be unregistered and not return (although this is not likely in my case). Perhaps the `IapetosRegistry` protocol could forward the `clear` and `unregister` methods to the underlying Prometheus registry?

On sum, though, I'm perfectly happy with things as they are. Many thanks!
