### ISSUE TITLE
Next planned release?

### ISSUE THREAD

**Issue by scizo** [clj-commons/iapetos#17]
I apologize if creating an issue isn't the best way to ask this question, but I was wondering if you were planning on releasing 1.8.0 anytime soon? I would love to use your `unregister` functionality that you have added.

Thanks for the library!

**Comment by xsc** [comment]
Released! Sorry for the delay, busy times these days. :)

[Release Notes](https://github.com/xsc/iapetos/releases/tag/v0.1.8)

**Comment by scizo** [comment]
Thanks for the quick response and don't apologize. :smiley:
