### ISSUE TITLE
choose where to publish jars 

### ISSUE THREAD

**Issue by MalloZup** [clj-commons/iapetos#24]
need discussion with org

**Comment by MalloZup** [comment]
@xsc if you grant me the access to https://clojars.org or @danielcompton @slipset  we might need to move the jars to clj-common namespace. Could someone add my user there perhaps?

In any case feel free to ping me either via slack or mail

**Comment by danielcompton** [comment]
Looks like we're going to move to clj-commons for this, might pay to point this out the change prominently in the README so that people spot that they need to upgrade.

**Comment by MalloZup** [comment]
Right thx Daniel can you send a pr for this? Im outside with the dog 🐶

**Comment by MalloZup** [comment]
This issue is solved closing however the Readme need update about the change feel free to send pr for that tia
