### ISSUE TITLE
investigate about codecoverage migration

### ISSUE THREAD

**Issue by MalloZup** [clj-commons/iapetos#28]
the codecoverage in readme point to the old repo.

We should investigate if we can enable that service here, and ask maybe to clj-common about this, if it is possible.

Currenlty I never setted up such service

**Comment by caioguedes** [comment]
@MalloZup, seems that post step on [Travis CI](https://travis-ci.org/github/clj-commons/iapetos/jobs/732098076#L422) stop working after a old commit, with `:pedantic? :abort` enabled for all profiles.

So I just changed the option on `coverage` profile to `:warn`, and it may fix the problem.

**Comment by MalloZup** [comment]
great thx!
