### ISSUE TITLE
Update Java Simple Client Dependencies

### ISSUE THREAD

**Issue by vise890** [clj-commons/iapetos#3]
Hi,

I added the `[io.prometheus/simpleclient_hotspot "0.0.19"]` as specified in the README, but i was greeted by a `java.lang.NoClassDefFoundError: io/prometheus/client/SummaryMetricFamily` when trying to access the `/metrics` endpoint.

Adding `[io.prometheus/simpleclient "0.0.19"]` to the deps as well fixed the problem for me. 

Am I doing something wrong? Is it just a case of updating the readme?

**Comment by xsc** [comment]
@vise890 iapetos depends on version 0.1.15 of `simpleclient`, so it's probable that `simpleclient_hotspot` 0.1.19 uses stuff from `simpleclient` that was added somewhere between 0.1.15 and 0.1.19.

You're not doing anything wrong, adding the explicit `simpleclient` dependency or using `simpleclient_hotspot` 0.1.15 would be my recommended course of action until iapetos' dependencies have been updated.

Feel free to open a PR with the dependency bumps. :)

**Comment by vise890** [comment]
ah ok, nice. 

Hopefully I'll have some time to open a PR, unfortunately just bumping the deps breaks a few tests :(

**Comment by xsc** [comment]
@vise890 I'll check it out! For now, you should probably just use 0.1.15.

**Comment by xsc** [comment]
The dependencies have been upgraded in version `0.1.3`. :)
