### ISSUE TITLE
index documentatoin of readme

### ISSUE THREAD

**Issue by MalloZup** [clj-commons/iapetos#35]
Right now the readme.md of iapetos is a big file

it would be nice if we can provide a schema like this

# iapetos 

Table of contents
- [bo](#bo)
- [foo](#foo)

with links on titles

**Comment by michellymenezes** [comment]
Hey, just opened regarding this issue.
https://github.com/clj-commons/iapetos/pull/50

**Comment by MalloZup** [comment]
was fixed. closing
