### ISSUE TITLE
get a release version `0.1.10`

### ISSUE THREAD

**Issue by MalloZup** [clj-commons/iapetos#45]
Can we get a release version `0.1.10` for this change please?

Only able to find `[clj-commons/iapetos "0.1.9"]`, in repositories and that version has this problem when using push-gateway. I had to manually include `io.prometheus` version `0.8.0` in my project

_Originally posted by @WarFox in https://github.com/clj-commons/iapetos/pull/38#issuecomment-646597887_

**Comment by slipset** [comment]
Sorry, I've dropped these. `0.1.11` is now in clojars. cc @erez-rabih
